stages:
  data_ingestion:
    cmd: python src\components\data_ingestion.py
    deps:
    - src\components\data_ingestion.py
    outs:
    - artifacts/__MACOSX
    - artifacts/MetaMotion
    - artifacts/data.zip
  data_transformation:
    cmd: python src/components/data_transformation.py
    deps :
    - artifacts/MetaMotion
    - src/components/data_transformation.py
    outs:
    - artifacts/transformed_data.pkl
  outlier_removal:
    cmd: python src/components/outlier_removal.py
    deps: 
    - artifacts/transformed_data.pkl
    - src/components/outlier_removal.py
    outs:
    - artifacts/outlier_removed_chauvenet.pkl
  feature_engineering:
    cmd: python src/components/build_features.py
    deps:
    - artifacts/outlier_removed_chauvenet.pkl
    - src/components/build_features.py
    outs:
    - artifacts/feature_engineered_data.pkl
  data_modeling:
    cmd: python src/components/data_modeling.py
    deps:
    - src/components/data_modeling.py
    - artifacts/feature_engineered_data.pkl
    params:
    - random_forest.min_samples_leaf
    - random_forest.n_estimators
    - random_forest.criterion
    outs:
    - artifacts/fitness_tracker.joblib
    metrics:
    - model_metrics.json


    